ben-manes/caffeine

jcache/src/main/java/com/github/benmanes/caffeine/jcache/CacheProxy.java
should divide by 1000000 (>> 20 => 1048576) not 1000 (>> 10 => 1024)
=> currentTimeMillis() was returning microsecondonds

README.md
Spring Boot 1.4 has very recently been released as is mentioned [here](https://spring.io/blog/2016/07/28/spring-boot-1-4-released)
=> Removed 'upcoming' word from Spring Boot integration documentation

simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/two_queue/TwoQueuePolicy.java
This 2Q implementation was the best I found to evaluate a C based 2Q
implementation that I have been working on.  With this change the
behavior is the same on several workloads at several data-points.
It took a lot of debugging to track this down :-)
=> Insert into the hashtable when evicting from Am.

jcache/src/main/java/com/github/benmanes/caffeine/jcache/event/EventTypeAwareListener.java
I ran into a problem where an IllegalStateException was being thrown every time my event listeners were invoked.
```
Jul 02, 2017 9:30:20 PM com.github.benmanes.caffeine.jcache.event.EventTypeAwareListener dispatch
WARNING: null
java.lang.IllegalStateException: Unknown event type: REMOVED
at com.github.benmanes.caffeine.jcache.event.EventTypeAwareListener.dispatch(EventTypeAwareListener.java:80)
at com.github.benmanes.caffeine.jcache.event.EventDispatcher.lambda$publish$2(EventDispatcher.java:215)
at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687)
at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
at …
```
=> Fix IllegalStateException being thrown for all event types.

jcache/src/main/java/com/github/benmanes/caffeine/jcache/CacheProxy.java, jcache/src/test/java/com/github/benmanes/caffeine/jcache/CacheProxyTest.java
We are using Caffeine with JCache and need access to the native Caffeine cache to register it with [Prometheus](https://github.com/prometheus/client_java/blob/master/simpleclient_caffeine/src/main/java/io/prometheus/client/cache/caffeine/CacheMetricsCollector.java). The current implementation just returns itself.
This is very similar to the way [Ehcache](https://github.com/ehcache/ehcache-jcache/blob/598c609d3f1d5addcdb866f64b37b9769d2fd97b/ehcache-jcache/src/main/java/org/ehcache/jcache/JCache.java#L726-L732) is doing it.
=> Allow unwrapping of a JCache cache to a native Caffeine cache

jcache/src/main/java/com/github/benmanes/caffeine/jcache/CacheFactory.java, jcache/src/test/java/com/github/benmanes/caffeine/jcache/expiry/JCacheExpiryAndMaximumSizeTest.java
The ```eager-expiration``` will not take affect with the following configuration 
```
test-cache {
policy {
eager-expiration {
after-write = 10m
}
maximum {
size = 1000
}
}
}
```
As you can see by this [code](https://github.com/ben-manes/caffeine/blob/master/jcache/src/main/java/com/github/benmanes/caffeine/jcache/CacheFactory.java#L159-L161).
```
boolean evicts = configureMaximumSize() || configureMaximumWeight()
|| configureExpireAfterWrite() || configureExpireAfterAccess()
|| configureExpireVariably();
```
The first configuration that it finds is the only one that gets configured.
I looked at passing mocks into ```CacheFactory``` but doesn't seem possible since the configuration gets cloned. So please let me know if there is a better way I should be testing this.
=> Allow configuration of max size and expiry simultaneously for JCache

caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/NodeFactoryGenerator.java, caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/NodeSelectorCode.java, caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/Specifications.java, caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/node/AddConstructors.java, caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/node/AddFactoryMethods.java, caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/node/AddSubtype.java, caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/node/Finalize.java, caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/node/NodeContext.java, caffeine/src/test/java/com/github/benmanes/caffeine/cache/IsCacheReserializable.java
How about this: make the node class a factory for itself :) (details in the commit message)
Zero reflection on the fast path + 90KB classes less.
It is not how a real gentleman would structure their Java code but the circumstances are extreme :)
=> Make a Node a factory for itself

caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/LocalCacheFactoryGenerator.java, caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/LocalCacheSelectorCode.java, caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/NodeFactoryGenerator.java, caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/NodeSelectorCode.java, caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/Specifications.java, caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/local/AddSubtype.java, caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/node/AddSubtype.java
If nested, every method/class/field descriptor carries
the enclosing's class name and a $ sign.
Also slightly shorter name using french words to avoid name
collisions.
=> Generate top-level classes for Nodes and Factories

caffeine/src/main/java/com/github/benmanes/caffeine/cache/Caffeine.java
Caffeine uses a ConcurrentHashMap under the hood. The way this works is that there are a number of bins, and the bins contain nodes (which contain 0 or more k/v pairs).
When I do a compute or computeIfAbsent, I look for the bin my node should be in, and if it does not exist, I put a placeholder bin there, compute, and then put the value there. If it does exist, I lock the bin, do whatever checks I need to do, put the value if necessary and unlock.
When I am done, I grow the map if necessary (generally increasing it by powers of 2).
Caffeine's default map size is 0, which cases the ConcurrentHashMap to be created with no table. This is cheap, but has the drawback of Caffeine starting off with only 2 buckets.
The issue here is that when I do a computeIfAbsent call, it synchronizes with …
=> Change Caffeine default cache size to 64

examples/coalescing-bulkloader/pom.xml, examples/coalescing-bulkloader/src/main/java/com/github/benmanes/caffeine/examples/coalescing/bulkloader/CoalescingBulkloader.java, examples/coalescing-bulkloader/src/test/java/com/github/benmanes/caffeine/examples/coalescing/bulkloader/CoalescingBulkloaderTest.java, travis.sh
Hey Ben,
Looks like you merged without taking the changes?
Anyway, here's the PR again. Better luck this time!
cheers, Guus
=> Coalescing bulkloader sample

settings.gradle
It disables the plugin in case `dependencyUpdates` is on the task execution graph (the set of tasks is configurable via `checksumIgnoreOnTask` property)
=> Bump checksum-dependency-plugin to 1.30.0

checksum.xml, settings.gradle
v1.31.0, v1.33.0, v1.35.0 reduce the verbosity when downloading keys.
v1.31.0 adds `-PchecksumUpdateAll` property (==update `checksum.xml`, avoid failures)
I use `caffeine / allDependencies` for regression tests of `checksum-dependency-plugin`, so I would like the task to be working: https://travis-ci.org/vlsi/vlsi-release-plugins/jobs/609652585#L444-L444
=> Bump checksum-dependency-plugin -> 1.44, fix allDependencies

simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/AccessEvent.java, simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/PolicyStats.java, simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/linked/LinkedPolicy.java, simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/product/Cache2kPolicy.java, simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/product/CaffeinePolicy.java, simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/product/ElasticSearchPolicy.java, simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/product/GuavaPolicy.java, simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/report/CsvReporter.java, simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/report/TableReporter.java, simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/report/TextReporter.java
I changed the linked policies (LRU, MRU, FIFO, Clock) to be able to work with weighted traces.
I validate that they work the same as before for unweighed traces, and the new implementation has identical results to [webcachesim](https://github.com/dasebe/webcachesim) simulator (for LRU and FIFO).
Notice that if the admission policy is not Always, the behavior is to evict victims one by one as long as the candidate wins and admit when there is enough space (similar to [Ristretto](https://github.com/dgraph-io/ristretto) approach and not to Caffeine current approach).
=> Make linked policies simulation weight-aware

gradle/publish.gradle
Both URLs were missing the [provider] part (here "git"), see https://maven.apache.org/pom.html#SCM.
Also, the connection URL must be usable for anonymous clones, so it should not contain a user name.
Finally, GitHub does not endorse the use of the "git" protocol, so use "ssh" for the authenticated developer
connection instead.
=> Fix SCM connection URLs when publishing

caffeine/src/main/java/com/github/benmanes/caffeine/cache/Node.java
The comment at `com.github.benmanes.caffeine.cache.Node#getVariableTime` is wrong.
=> Fix comment

simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/parser/TraceFormat.java, simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/parser/kaggle/OutbrainTraceReader.java, simulator/src/main/resources/reference.conf
A nice trace of Outbrain [provided](https://www.kaggle.com/c/outbrain-click-prediction/data) by Kaggle.
=> Add support for Outbrain traces

build.gradle, checksum.xml, gradle/dependencies.gradle, jcache/build.gradle, jcache/src/main/java/com/github/benmanes/caffeine/jcache/CacheManagerImpl.java, jcache/src/main/java/com/github/benmanes/caffeine/jcache/spi/CaffeineCachingProvider.java, jcache/src/test/java/com/github/benmanes/caffeine/jcache/OSGiTest.java
* annotated CaffeineCachingProvider to make it an OSGi service
* when running in an OSGi container, set the CaffeineCachingProvider's classloader as the Thread context classloader for every API call on the provided CacheManagerImpl - this makes sure that the default config is read from the bundle; the default classloader will do a fallback to the app classloader, allowing to override / define configurations
* added an OSGi DS test
* made the bnd build reproducible (no extra bundle headers)
(fixes #447)
=> fix #447: Allow the CaffeineCachingProvider to be used with OSGi DS

caffeine/src/main/java/com/github/benmanes/caffeine/cache/Caffeine.java
The `maximumWeight` builder method is the only method that does the argument verification before the assignment.
It looks like a typo, and does not affect anyone in practice, but it is still better to have the implementation uniform.
=> Verify maximumWeight before setting

simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/Registry.java, simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/irr/ClockProPlusPolicy.java, simulator/src/main/resources/reference.conf
- It seems dirty, but I just copied and pasted the ClockPro code and modified parts of adjusting coldTarget. This is because the noise issue still remaining in ClockPro algorithm, so I wanted to keep the code as easy as possible to modify and test without depending on other files.
- ClockPro's default configuration has been changed as we discussed
=> Add ClockProPlus policy

caffeine/build.gradle, caffeine/src/main/java/module-info.java, gradle/codeQuality.gradle, gradle/dependencies.gradle, guava/build.gradle, jcache/build.gradle, simulator/build.gradle
Considering it was noted that the module descriptor broke usage in Eclipse/buildship, I took care to ensure that Caffeine can still compile in Eclipse.
I developed and tested this solution using Eclipse 2021-03 (4.19.0). It relies on the Module Dependencies tab of the project build path menu to fix compilation in Eclipse/buildship.
Hamcrest v1 had to be excluded from transitive dependencies since it lead to a split package clash.
FastUtil had to be downgraded to 8.5.2 because of split packages: https://github.com/vigna/fastutil/issues/245
Resolves #535
=> Add module descriptor while keeping workable Eclipse IDE experience

simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/Registry.java, simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/irr/ClockProSimplePolicy.java, simulator/src/main/resources/reference.conf
It is a simple implementation of ClockPro, but using more memory (8bytes per metadata).
=> Add simplified ClockPro policy

examples/coalescing-bulkloader/src/main/java/com/github/benmanes/caffeine/examples/coalescing/bulkloader/CoalescingBulkloader.java, examples/coalescing-bulkloader/src/test/java/com/github/benmanes/caffeine/examples/coalescing/bulkloader/CoalescingBulkloaderTest.java
for https://github.com/ben-manes/caffeine/issues/7#issuecomment-956281417
made more fields final
applied google formatter
gave the tests more slack to also succeed consistently on Windows 10
=> same fixes as yesterday

examples/coalescing-bulkloader/src/main/java/com/github/benmanes/caffeine/examples/coalescing/bulkloader/CoalescingBulkloader.java
Bulk loading is expected to be a time-consuming operation. During bulk loading, other threads may invoke the method "doLoad" which is unnecessary, because the queue size is still larger than maxLoadSize. These threads will invoke "doLoad" immediately after finishing pervious "doLoad" but load nothing.
So moving the reduce-queue-size operation before the bulk-load operation will not cause the problem above.
=> Reorder the operation of reducing size before that of bulk loading

README.md
`https://code.google.com/p/concurrentlinkedhashmap` doesn't always redirect - and even when it does :)
=> Update concurrentlinkedhashmap link

README.md
Kotlin-based Gradle files are quite popular now, providing an example that works for both `Groovy` (.gradle) *and* `Kotlin` (`.gradle.kts`) may slightly simplify trying out the library.
=> Update Gradle example to be Groovy & Kotlin compatible

simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/parser/snia/keyvalue/ObjectStoreTraceReader.java
The object store trace contains some range reads events with invalid ending offset leading to events with negative weight.
For example, the following events in `IBMObjectStoreTrace001Part0`:
```
192199064 REST.GET.OBJECT 6c44b4d75e985008 0 0 -1
192199064 REST.GET.OBJECT fb7caa17fb475a5c 0 0 -1
192200755 REST.GET.OBJECT 12c21c4f26736f15 0 0 -1
192200755 REST.GET.OBJECT a8a514e89f0ff7aa 0 0 -1
```
This PR filters these events as part of the reader to avoid pre-processing the input file
=> Filter invalid event in object store trace

simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/parser/snia/keyvalue/ObjectStoreTraceReader.java
This PR fixes a minor issue with the condition checking for GET requests without range reads.
In addition, since the reader filters only GET requests, I am not sure that the condition is needed at all, I haven't seen any GET request in the traces without range reads so it seems that this condition was never met anyway.
Maybe @ohadeytan knows if there are such cases.
=> fix minor issue with array length condition in object storage traces

build.gradle, gradle/dependencies.gradle
This prevents junit-bom from becoming a dependency of caffeine's published artifacts
=> Include the junit platform via a test implementation

caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalCacheFactory.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/NodeFactory.java
This is to work around a possible concurrency bug in JDK.
This closes #1111
=> Fix issue #1111 by not creating MethodType on each invocation

README.md
This PR only gives the caffeine project the right to display the badge in this particular situation, as a badge in the project README.
=> Add `Revved up by Gradle Enterprise` badge

jcache/src/main/java/com/github/benmanes/caffeine/jcache/configuration/TypesafeConfigurator.java
As mentioned in [#1347](https://github.com/ben-manes/caffeine/issues/1347), the URIs in case of JakartaEE jar files are neither **file:** nor **classpath:** but **jar:**.
Extend the TypesafeConfigurator#resolveConfig to properly pass also jar: protocol URLs, so the Caffeine can be used as Hibernate's 2nd level cache in complex JakartaEE applications.
=> #1347 - Fix for hibernate.javax.cache.uri in JakartaEE EARs

gradle/gradle-enterprise.gradle
Updated remote build cache config to only push when authenticated -> if an unauthenticated push is attempted remote build cache will get turned off for the rest of the build. This can happen (does) on forked PR builds which run in an unsecure environment.
=> Set remote build cache to push only if authenticated

.github/actions/run-gradle/action.yml, .github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/dependency-review.yml, .github/workflows/dependency-submission-pr-retreive.yml, .github/workflows/dependency-submission-pr-submit.yml, .github/workflows/examples.yml, .github/workflows/qodana.yml, .github/workflows/release.yml, .github/workflows/scorecards-analysis.yml, .github/workflows/semgrep.yml, examples/coalescing-bulkloader-reactor/gradle/libs.versions.toml, examples/coalescing-bulkloader-reactor/gradle/wrapper/gradle-wrapper.properties, examples/graal-native/gradle/libs.versions.toml, examples/graal-native/gradle/wrapper/gradle-wrapper.properties, examples/hibernate/gradle/libs.versions.toml, examples/hibernate/gradle/wrapper/gradle-wrapper.properties, examples/resilience-failsafe/gradle/libs.versions.toml, examples/resilience-failsafe/gradle/wrapper/gradle-wrapper.properties, examples/write-behind-rxjava/gradle/libs.versions.toml, examples/write-behind-rxjava/gradle/wrapper/gradle-wrapper.properties, gradle/libs.versions.toml, gradle/plugins/build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
PR to test the integration of `dependency-submission` with the `dependency-review-action`
=> migrate to the new setup-gradle and dependency-submission actions

caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncCache.java, caffeine/src/test/java/com/github/benmanes/caffeine/cache/AsyncLoadingCacheTest.java
Fixes #1409.
Verified by running the `getAll_exceeds` test with the `ForkJoinPool` executor. Running this test configuration before the change would fail sporadically due to a race between the excess entries being added to the cache and the cache size assertion.
=> When `AsyncCacheLoader.asyncLoadAll` returns excess keys, wait for all keys to be added to the cache before returning requested keys

README.md
A specific Bootique/Caffeine example is provided here: https://github.com/bootique-examples/bootique-jcache-examples/tree/3.x/jcache-caffeine-example
=> Adding Bootique to the list of projects that work with Caffeine

caffeine/src/test/java/com/github/benmanes/caffeine/cache/issues/Issue30Test.java
Fixes #1788
Regarding the change `h` ('clock-hour-of-am-pm (1-12)') to `H` ('hour-of-day (0-23)'):
Maybe the usage of `h` was intended before, since it is also using the `US` locale, however then maybe it should have included the am/pm marker?
=> Fix incorrect date format pattern in unit test

caffeine/src/main/java/com/github/benmanes/caffeine/cache/AsyncCache.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/AsyncCacheLoader.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/AsyncLoadingCache.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/Cache.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/CacheLoader.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/LoadingCache.java
https://github.com/ben-manes/caffeine/commit/2542ca8ca22fe4c30b62ee569ee71436fc44a37e
changed types like the return type of `Cache.get` to be non-null instead
of unspecified.
As discussed in https://github.com/ben-manes/caffeine/issues/594, the
types really "should" be nullable, but that is inconvenient for most
users.
When Caffeine was using Checker Framework annotations, it could use
`@PolyNull` to give Checker Framework users the best of both worlds and
give users of other tools (notably Kotlin) a convenient (if not fully
strict) experience, since those tools viewed the types as having
unspecified nullness (in Kotlin terms, "platform types").
Caffeine could still use `@PolyNull` today if you want to restore the
Checker Framework dependency. (And maybe someday JSpecify will include
its …
=> Avoid giving the result of loads a non-null type.

caffeine/src/main/java/com/github/benmanes/caffeine/cache/AsyncCache.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/AsyncCacheLoader.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/AsyncLoadingCache.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/Cache.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/CacheLoader.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/Caffeine.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/LoadingCache.java, jcache/src/main/java/com/github/benmanes/caffeine/jcache/CacheFactory.java, jcache/src/main/java/com/github/benmanes/caffeine/jcache/CacheProxy.java, jcache/src/main/java/com/github/benmanes/caffeine/jcache/LoadingCacheProxy.java, jcache/src/main/java/com/github/benmanes/caffeine/jcache/integration/JCacheLoaderAdapter.java
This does not mean that the cache will "contain" `null`, since `null` is
never cached. However, it does allow users to declare whether they want
"a cache whose loads might return `null`" (which thus can return `null`
from cache operations) or "a cache whose loads will never return `null`"
(which thus doesn't require users to handle `null` when they request
that the cache return or load a value).
This PR follows up on https://github.com/ben-manes/caffeine/pull/1805.
Ideally I will come back to write some Kotlin tests for this. For the
moment, I can only say that the results look good in my testing inside
Google.
=> Allow caches to have nullable type arguments for their value types.

caffeine/src/jmh/java/com/github/benmanes/caffeine/cache/impl/Cache2k.java
This addresses a warning NullAway will start reporting once https://github.com/uber/NullAway/pull/1144 lands
=> Add @Nullable annotation in Cache2k to fix upcoming NullAway warning

caffeine/src/main/java/com/github/benmanes/caffeine/cache/AsyncCache.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/AsyncCacheLoader.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/AsyncLoadingCache.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/Cache.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/CacheLoader.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/LoadingCache.java
This PR belatedly explains the changes made in
https://github.com/ben-manes/caffeine/pull/1806, which have (sadly but
expectedly) required users to make changes in response, as discussed in
https://github.com/ben-manes/caffeine/issues/1826.
I'm still happy to assist users with changes when it would be helpful,
but I hope that this documentation helps somewhat.
=> Update Javadoc to explain how to use nullness in type arguments in Caffeine 3.2.0.

caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/CaffeineSpec.java, caffeine/src/main/java/com/github/benmanes/caffeine/cache/UnboundedLocalCache.java, caffeine/src/test/java/com/github/benmanes/caffeine/cache/AsyncCacheTest.java, caffeine/src/test/java/com/github/benmanes/caffeine/testing/MapSubject.java, guava/src/main/java/com/github/benmanes/caffeine/guava/CaffeinatedGuavaCache.java, guava/src/main/java/com/github/benmanes/caffeine/guava/CaffeinatedGuavaLoadingCache.java, guava/src/test/java/com/github/benmanes/caffeine/guava/GuavaMapTests.java, jcache/src/main/java/com/github/benmanes/caffeine/jcache/CacheProxy.java, jcache/src/main/java/com/github/benmanes/caffeine/jcache/LoadingCacheProxy.java, jcache/src/main/java/com/github/benmanes/caffeine/jcache/copy/AbstractCopier.java, jcache/src/test/java/com/github/benmanes/caffeine/jcache/copy/JavaSerializationCopierTest.java
Found by locally compiling with a build of Error Prone with https://github.com/google/error-prone/pull/4828 applied and a NullAway branch that supports the unused suppression detection.  (Support for JdkObsolete was built into the Error Prone PR)
=> Remove some unneeded suppressions

caffeine/src/test/java/com/github/benmanes/caffeine/cache/AsyncTest.java, caffeine/src/test/java/com/github/benmanes/caffeine/cache/BoundedLocalCacheTest.java, caffeine/src/test/java/com/github/benmanes/caffeine/cache/issues/Issue568Test.java, simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/admission/clairvoyant/Clairvoyant.java
This is in preparation for uber/NullAway#1298, which causes new errors to be reported without these annotations.
=> Make contents of some AtomicReference variables @Nullable
